In [1]:
# Dependencies and Setup
#importing functions into jupter notebook...new seaborn package
import seaborn

import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
  

#DataFrame Creation
#house_market_df = pd.read_csv("areas_clean_Reviewed_10.24.22 - areas_clean.csv")
house_market_2018_df = pd.read_csv("2018_areas_clean_Reviewed_10.24.22 - areas_clean.csv")
house_market_2018final_df = pd.read_csv("2018_areas_clean_Reviewedfinal_10.24.22 - areas_clean.csv")
house_market_2019_df = pd.read_csv("2019_areas_clean_Reviewed_10.24.22 - areas_clean.csv")
house_market_2020_df = pd.read_csv("2020_areas_clean_Reviewed_10.24.22 - areas_clean.csv")
house_market_2021_df = pd.read_csv("2021_areas_clean_Reviewed_10.24.22 - areas_clean.csv")
house_market_2022_df = pd.read_csv("2022_areas_clean_Reviewed_10.24.22 - areas_clean.csv")

house_market_2018final_df

,Region,Month of Period End,Median Sale Price,Median Sale Price MoM,Median Sale Price YoY,Homes Sold,Homes Sold MoM,Homes Sold YoY,New Listings,New Listings MoM,...,Inventory,Inventory MoM,Inventory YoY,Days on Market,Days on Market MoM,Days on Market YoY,Average Sale To List,Average Sale To List MoM,Average Sale To List YoY,Year
0,30022,1/1/2018,371000.0,0.06,0.09,180.0,-0.19,-0.31,173.0,-0.06,...,178.0,-0.08,-0.31,38.0,1.0,-9.0,0.98,0.00,0.01,2018
1,30022,2/1/2018,376000.0,0.01,0.11,178.0,-0.01,-0.24,230.0,0.33,...,169.0,-0.05,-0.39,39.0,2.0,-10.0,0.98,0.00,0.01,2018
2,30022,3/1/2018,375000.0,0.00,0.08,221.0,0.24,-0.10,354.0,0.54,...,207.0,0.23,-0.36,31.0,-9.0,-23.0,0.99,0.01,0.01,2018
3,30022,4/1/2018,386000.0,0.03,0.09,297.0,0.34,0.02,447.0,0.26,...,246.0,0.19,-0.22,20.0,-11.0,-27.0,0.99,0.00,0.01,2018
4,30022,5/1/2018,392000.0,0.01,0.08,338.0,0.14,-0.03,496.0,0.11,...,282.0,0.15,-0.12,18.0,-2.0,-17.0,0.99,0.00,0.01,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,30625,8/1/2018,320000.0,-0.11,-0.09,11.0,-0.08,-0.31,16.0,0.14,...,21.0,0.05,-0.30,109.0,35.0,-92.0,1.00,0.01,0.05,2018
92,30625,9/1/2018,320000.0,0.00,-0.02,11.0,0.00,0.10,17.0,0.06,...,22.0,0.05,-0.15,74.0,-35.0,-47.0,0.97,-0.03,0.01,2018
93,30625,10/1/2018,320000.0,0.00,-0.07,10.0,-0.09,-0.09,16.0,-0.06,...,21.0,-0.05,-0.09,110.0,36.0,-87.0,0.96,-0.01,0.00,2018
94,30625,11/1/2018,418000.0,0.31,0.14,8.0,-0.20,0.00,13.0,-0.19,...,21.0,0.00,-0.09,59.0,-52.0,-48.0,0.98,0.02,0.01,2018
95,30625,12/1/2018,445000.0,0.07,0.26,5.0,-0.38,-0.62,9.0,-0.31,...,20.0,-0.05,0.05,64.0,6.0,-108.0,0.97,-0.01,0.01,2018

In [ ]:
# house_market_2018_df.info()

In [ ]:
# house_market_2018_df.columns

In [ ]:
# house_market_2018_df['Median Sale Price'] = house_market_2018_df['Median Sale Price'].str.strip('$').str.replace(',','').astype('float')
# #house_market_2018_df['Inventory MoM'] = house_market_2018_df['Inventory MoM'].str.strip('%').astype('float')
# house_market_2018_df['Inventory YoY'] = house_market_2018_df['Inventory YoY'].str.strip('%').astype('float')
# #house_market_2018_df['Homes Sold MoM'] = house_market_2018_df['Homes Sold MoM'].str.strip('%').astype('float')
# #house_market_2018_df['Median Sale Price YoY'] = house_market_2018_df['Median Sale Price YoY'].str.strip('%').astype('float')
# #end_of_inventory = house_market_df['Homes Sold'] + house_market_df['Inventory']
# # house_market_2018_df['Total Available Homes']=house_market_2018_df['Homes Sold'] + house_market_2018_df['Inventory']
# # house_market_2018_df['MOI']= house_market_2018_df['Homes Sold'] / house_market_2018_df['Inventory']
# house_market_2018_df.head()

In [ ]:
#house_market_df['Month of Period End']

#pd.to_datetime(house_market_df['Month of Period End'], format = "%b-%y").dt.year

#house_market_df['Month of Period End'].dt.year

In [ ]:
# pairplot based on column we choose for color scheme...will try Region
seaborn.pairplot(house_market_2018final_df,hue="Region")
# to show
plt.show()

In [ ]:
plt.savefig('Data_Junkies_2018pairplot.png')

In [ ]:
#set dataframe by year
#Dataset ranges from 2012 - 2022
#DataFrame 2018
#
#house_market_df['year'] = pd.DatetimeIndex(house_market_df['Month of Period End']).year

# convert a series to list 
#year = house_market_df['year'].tolist()
#n = len(year)

#
#year_list = []
#counter = 0
#for i in range(0,10): 
#    year_list.append(house_market_df.loc[house_market_df['year'] == (2012 + i)])
#year_list

#Display Results
#house_market_df.head()

#DataFrame 2019